-- MySQL Script generated by MySQL Workbench
-- Mon Sep 11 21:37:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema startup_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema startup_management_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `startup_management_system` DEFAULT CHARACTER SET utf8 ;
USE `startup_management_system` ;

-- -----------------------------------------------------
-- Table `startup_management_system`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `startup_management_system`.`admin` (
  `loginEmail` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `registration_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`loginEmail`),
  UNIQUE INDEX `loginEmail_UNIQUE` (`loginEmail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `startup_management_system`.`startup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `startup_management_system`.`startup` (
  `name` VARCHAR(255) NOT NULL,
  `registration_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `budget` DECIMAL(10,2) NULL DEFAULT 0.00,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `registration_date_UNIQUE` (`registration_date` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `startup_management_system`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `startup_management_system`.`user` (
  `loginEmail` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `registration_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `capital` DECIMAL(10,2) NULL DEFAULT 0.00,
  PRIMARY KEY (`loginEmail`),
  UNIQUE INDEX `loginEmail_UNIQUE` (`loginEmail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `startup_management_system`.`contribution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `startup_management_system`.`contribution` (
  `id` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `transaction_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `amount` DECIMAL(10,2) NULL DEFAULT 0.00,
  `login_email` VARCHAR(50) NOT NULL,
  `startup_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_contribution_user1_idx` (`login_email` ASC),
  INDEX `fk_contribution_startup1_idx` (`startup_name` ASC),
  CONSTRAINT `fk_contribution_user1`
    FOREIGN KEY (`login_email`)
    REFERENCES `startup_management_system`.`user` (`loginEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contribution_startup1`
    FOREIGN KEY (`startup_name`)
    REFERENCES `startup_management_system`.`startup` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `startup_management_system`.`user_has_startup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `startup_management_system`.`user_has_startup` (
  `user_loginEmail` VARCHAR(50) NOT NULL,
  `startup_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_loginEmail`, `startup_name`),
  INDEX `fk_user_has_startup_startup1_idx` (`startup_name` ASC),
  INDEX `fk_user_has_startup_user_idx` (`user_loginEmail` ASC),
  CONSTRAINT `fk_user_has_startup_user`
    FOREIGN KEY (`user_loginEmail`)
    REFERENCES `startup_management_system`.`user` (`loginEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_startup_startup1`
    FOREIGN KEY (`startup_name`)
    REFERENCES `startup_management_system`.`startup` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
